/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.Action;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import model.grade;
import model.gradeDAO;

import database.DattabaseUtils;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.util.Properties;
import javax.swing.JFileChooser;

import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import jxl.Workbook;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.Number;
import model.SinhVienDAO;
import model.UserDAO;

/**
 *
 * @author Admin
 */
public class diem extends javax.swing.JPanel {

    DefaultTableModel model;
    List<grade> listdiem = new ArrayList<>();
    gradeDAO diemdao = new gradeDAO();
    String timkiem = "";
    private int selectedIndex;

    /**
     * Creates new form diem
     */
    public diem() {
        initComponents();
        laydulieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnxoa = new javax.swing.JButton();
        btntimkiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdiem = new javax.swing.JTable();
        btnsua = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();
        btndtxuatexcel = new javax.swing.JButton();
        btnguemail = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtpassword1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        txtnguoinhan1 = new javax.swing.JTextField();
        txtnguoigui1 = new javax.swing.JTextField();
        txttieude1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtnoidung1 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("DANH SÁCH SINH VIÊN");

        setBackground(new java.awt.Color(0, 204, 255));

        txttimkiem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txttimkiemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txttimkiemMouseEntered(evt);
            }
        });
        txttimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimkiemActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add.png"))); // NOI18N
        jButton1.setText("Thêm điểm mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("MSSV:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("DANH SÁCH ĐIỂM SINH VIÊN");

        btnxoa.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnxoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btntimkiem.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btntimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search.png"))); // NOI18N
        btntimkiem.setText("Tìm kiếm");
        btntimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemActionPerformed(evt);
            }
        });

        tbdiem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "MSSV", "Tên SV", "Toán", "Java", "Tiếng Anh", "ĐiểmTB", "Học Lực"
            }
        ));
        tbdiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdiemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbdiem);

        btnsua.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnsua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnreset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnreset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnreset.setText("Làm mới danh sách");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        btndtxuatexcel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btndtxuatexcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/excel.png"))); // NOI18N
        btndtxuatexcel.setText("Xuất Điểm");
        btndtxuatexcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndtxuatexcelActionPerformed(evt);
            }
        });

        btnguemail.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnguemail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Mail.png"))); // NOI18N
        btnguemail.setText("Gửi Điểm");
        btnguemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguemailActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Tiêu Đề:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Nội Dung:");

        txtpassword1.setText("tho123456");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Gmail Người Nhận:");

        txtnguoigui1.setText("bachtho2021");

        txttieude1.setText("BẢNG DIỂM");

        txtnoidung1.setColumns(20);
        txtnoidung1.setRows(5);
        jScrollPane2.setViewportView(txtnoidung1);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel10.setText("GMAIL");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Gmail Người Gửi:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("Password:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(20, 20, 20)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnguoigui1)
                                .addComponent(txtpassword1)
                                .addComponent(txtnguoinhan1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(txttieude1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(137, 137, 137)
                            .addComponent(jLabel10)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jLabel10)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(txtnguoigui1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtnguoinhan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(35, 35, 35)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txttieude1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(483, 483, 483)
                                .addComponent(jLabel3)))
                        .addGap(0, 91, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btntimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnguemail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btndtxuatexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btntimkiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(txttimkiem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnreset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsua, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btndtxuatexcel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguemail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public void laydulieu() {
        txtnguoigui1.setText(UserDAO.nguoidangnhap.getEmail());
        listdiem.clear();
        listdiem = diemdao.laydanhsachdiem();
        model = (DefaultTableModel) tbdiem.getModel();
        model.setRowCount(0);
        for (grade g : listdiem) {
            Object[] rowData = new Object[7];
            rowData[0] = g.getStudent().getMasv();
            rowData[1] = g.getStudent().getTensv();
            rowData[2] = g.getToan();
            rowData[3] = g.getJava();
            rowData[4] = g.getTiengAnh();
            String tb = String.format("%.2f", g.getDiemtb());
            rowData[5] = tb;
            rowData[6] = g.getXeploai();
            model.addRow(rowData);
        }
    }

    public void laydulieutheoma() {
        listdiem.clear();
        listdiem = diemdao.laydanhsachdiemtheomasv(timkiem);
        model = (DefaultTableModel) tbdiem.getModel();
        model.setRowCount(0);
        for (grade g : listdiem) {
            Object[] rowData = new Object[7];
            rowData[0] = g.getStudent().getMasv();
            rowData[1] = g.getStudent().getTensv();
            rowData[2] = g.getToan();
            rowData[3] = g.getJava();
            rowData[4] = g.getTiengAnh();
            String tb = String.format("%.2f", g.getDiemtb());
            rowData[5] = tb;
            rowData[6] = g.getXeploai();
            model.addRow(rowData);
        }
    }
    private void txttimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttimkiemMouseClicked

    }//GEN-LAST:event_txttimkiemMouseClicked

    private void txttimkiemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txttimkiemMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Themdiem sv = new Themdiem();
        sv.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if (txttimkiem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập mssv!!");
        } else if (diemdao.xoadiemtheomasv(txttimkiem.getText()) > 0) {
            JOptionPane.showMessageDialog(this, "Xóa thành công");
            laydulieu();
            this.txttimkiem.setText(null);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin cần xóa");
        }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemActionPerformed
        // TODO add your handling code here:
        if (txttimkiem.getText().equals("")) {
            laydulieu();
            JOptionPane.showMessageDialog(this, "Hãy nhập mã số sinh viên trước nhé");
        } else {
            timkiem = txttimkiem.getText();
            laydulieutheoma();
        }
    }//GEN-LAST:event_btntimkiemActionPerformed

    private void tbdiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdiemMouseClicked
        // TODO add your handling code here:   
        model = (DefaultTableModel) tbdiem.getModel();
        txttimkiem.setText(model.getValueAt(tbdiem.getSelectedRow(), 0).toString());
        try {
            int row = tbdiem.getSelectedRow();
            if (row >= 0) {
                String idsv = (String) tbdiem.getValueAt(row, 0);
                SinhVienDAO dao = new SinhVienDAO();
                SinhVien sv = dao.laysvkhongcanlop(idsv);
                String idbd = (String) tbdiem.getValueAt(row, 0);
                gradeDAO bddao = new gradeDAO();
                grade bd = bddao.getgradebymasv(idbd);
                String tb = String.format("%.2f", bd.getDiemtb());
                if (sv != null || bd != null) {
                    txtnguoinhan1.setText(sv.getEmail());
                    txtnoidung1.setText("MSSV: " + sv.getMasv()
                            + "\nHọ Tên SV: " + sv.getTensv()
                            + "\nĐiểm Java: " + bd.getJava()
                            + "\nĐiểm Toán: " + bd.getToan()
                            + "\nĐiểm Tiếng Anh: " + bd.getTiengAnh()
                            + "\nĐiểm TB: " + tb
                            + "\nHọc lực: " + bd.getXeploai()
                            + "\nNếu có sai sót gì báo cáo giảng viên ngay !!");
                }
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_tbdiemMouseClicked

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        selectedIndex = tbdiem.getSelectedRow();
        if (listdiem.size() == 0) {
            JOptionPane.showMessageDialog(this,
                    "Hãy nhập thêm sinh viên rồi sửa!");
        } else if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this,
                    "Hãy chọn dòng có sinh viên cần sửa rồi ấn Sửa!");
        } else { // chon dong can sua va nhan nut
            Suadiem edit = new Suadiem();
            edit.setEditData(listdiem.get(selectedIndex));
            edit.setVisible(true);
        }
    }//GEN-LAST:event_btnsuaActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        // TODO add your handling code here:
        laydulieu();
    }//GEN-LAST:event_btnresetActionPerformed

    private void btndtxuatexcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndtxuatexcelActionPerformed
        int dong = tbdiem.getRowCount();
        if (dong <= 0) {
            return;
        }
        try {
            JFileChooser savefile = new JFileChooser();
            int result = savefile.showSaveDialog(btndtxuatexcel);
            if (result != JFileChooser.APPROVE_OPTION) {
                return;
            }
            File fileToSave = savefile.getCurrentDirectory();
            String link = fileToSave.getPath();
            String ten = savefile.getSelectedFile().getName();
            String linksave = link + "\\" + ten + ".xls";

            WritableWorkbook workbook = Workbook.createWorkbook(new File(linksave));
            WritableSheet sheet = workbook.createSheet("BẢNG ĐIỂM SINH VIÊN ", 0);
            sheet.addCell(new Label(0, 0, "Mã Sinh Viên"));
            sheet.addCell(new Label(1, 0, "Tên Sinh Viên"));
            sheet.addCell(new Label(2, 0, "Điểm Toán"));
            sheet.addCell(new Label(3, 0, "Điểm Java"));
            sheet.addCell(new Label(4, 0, "Điểm Tiếng Anh"));
            sheet.addCell(new Label(5, 0, "Điểm TB"));
            sheet.addCell(new Label(6, 0, "Xếp Loại"));

            for (int i = 1; i <= dong; i++) {
                sheet.addCell(new Label(0, i, tbdiem.getValueAt(i - 1, 0).toString()));
                sheet.addCell(new Label(1, i, tbdiem.getValueAt(i - 1, 1).toString()));
                sheet.addCell(new Label(2, i, tbdiem.getValueAt(i - 1, 2).toString()));
                sheet.addCell(new Label(3, i, tbdiem.getValueAt(i - 1, 3).toString()));
                sheet.addCell(new Label(4, i, tbdiem.getValueAt(i - 1, 4).toString()));
                sheet.addCell(new Label(5, i, tbdiem.getValueAt(i - 1, 5).toString()));
                sheet.addCell(new Label(6, i, tbdiem.getValueAt(i - 1, 6).toString()));

            }
            workbook.write();
            workbook.close();
            JOptionPane.showMessageDialog(this, "Xuất file thành công!!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi: " + e);
        }

    }//GEN-LAST:event_btndtxuatexcelActionPerformed

    private void btnguemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguemailActionPerformed
        // TODO add your handling code here:
        tbdiemMouseClicked(null);
        Properties prop = new Properties();
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", "587");
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true"); //TLS
        Session session = Session.getInstance(prop,
                new javax.mail.Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(txtnguoigui1.getText(), new String(txtpassword1.getPassword()));
            }
        });
        try {
            MimeMessage message = new MimeMessage(session);
            message.setFrom(new InternetAddress(txtnguoigui1.getText()));
            message.setRecipients(
                    Message.RecipientType.TO,
                    InternetAddress.parse(txtnguoinhan1.getText())
            );
            message.setSubject(txttieude1.getText());
            message.setText(txtnoidung1.getText());

            Transport.send(message);
            JOptionPane.showMessageDialog(this, "gửi thành công");
            System.out.println("Done");

        } catch (MessagingException e) {
            e.printStackTrace();
        }
        //}
    }//GEN-LAST:event_btnguemailActionPerformed

    private void txttimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimkiemActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndtxuatexcel;
    private javax.swing.JButton btnguemail;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btntimkiem;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbdiem;
    private javax.swing.JTextField txtnguoigui1;
    private javax.swing.JTextField txtnguoinhan1;
    private javax.swing.JTextArea txtnoidung1;
    private javax.swing.JPasswordField txtpassword1;
    private javax.swing.JTextField txttieude1;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
