/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.SinhVien;
import model.SinhVienDAO;
import model.lopDAO;
import model.lop;

/**
 *
 * @author Admin
 */
public class Themsv extends javax.swing.JDialog {
    lopDAO sv = new lopDAO();
    SinhVienDAO dao = new SinhVienDAO();
    ButtonGroup rdg = new ButtonGroup();
    DefaultTableModel model;
    List<SinhVien> lsD = new ArrayList<>();
    public ArrayList<SinhVien> listStudent = new ArrayList<>();

    /**
     * Creates new form Themsv
     */
    public Themsv() {
        // super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        rdg.add(rdnam);
        rdg.add(rdnu);
        this.setTitle("Nhập thông tin ");
        loadcombobox();
    }

    public void loadcombobox() {
        Connection con = database.DattabaseUtils.getDBConnect();
        String sSQL = " select *  FROM lop";
        try {
            PreparedStatement sttm = con.prepareStatement(sSQL);
            ResultSet rs = sttm.executeQuery();
            while (rs.next()) {
                this.cbblop.addItem(rs.getString("malop"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnluu = new javax.swing.JButton();
        rdnu = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        txtmasv = new javax.swing.JTextField();
        txthoten = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdiachi = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdnam = new javax.swing.JRadioButton();
        tbmssv = new javax.swing.JLabel();
        tbsđt = new javax.swing.JLabel();
        tbemail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbblop = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);

        btnluu.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnluu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Save as.png"))); // NOI18N
        btnluu.setText("Thêm");
        btnluu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluuActionPerformed(evt);
            }
        });

        rdnu.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        rdnu.setText("Nữ");
        rdnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdnuActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Log out.png"))); // NOI18N
        jButton1.setText("Thoát");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtmasv.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtmasv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtmasv.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txthoten.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txthoten.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("SĐT:");

        txtsdt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtsdt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtemail.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("MSSV:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Địa Chỉ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Tên SV:");

        txtdiachi.setColumns(20);
        txtdiachi.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtdiachi.setRows(5);
        jScrollPane1.setViewportView(txtdiachi);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Giới Tính:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("NHẬP THÔNG TIN SINH VIÊN");

        rdnam.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        rdnam.setText("Nam");

        tbmssv.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tbsđt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Mã Lớp:");

        cbblop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbblopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdnam)
                                .addGap(10, 10, 10)
                                .addComponent(rdnu))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txthoten)
                                    .addComponent(cbblop, 0, 164, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tbemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtemail)
                            .addComponent(txtmasv, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(txtsdt)
                            .addComponent(tbmssv, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                            .addComponent(tbsđt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnluu)
                                    .addGap(37, 37, 37)
                                    .addComponent(jButton1))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(cbblop, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(tbmssv, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtsdt)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(5, 5, 5)
                .addComponent(tbsđt, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdnam)
                    .addComponent(rdnu)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbemail, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnluu, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public boolean check() {
        //kiem tra rong
        String id = txtmasv.getText();
        String ten = txthoten.getText();
        String email = txtemail.getText();
        String sdt = txtsdt.getText();
        String dc = txtdiachi.getText();
        if (id.length() == 0) {
            JOptionPane.showConfirmDialog(this, "Bạn chưa nhập MSSV!", "TB", JOptionPane.CLOSED_OPTION);
            txtmasv.requestFocus();
            txtmasv.setBackground(Color.red);
            return false;
        }
        if (ten.length() == 0) {
            JOptionPane.showConfirmDialog(this, "Bạn chưa nhập Tên sinh viên !", "TB", JOptionPane.CLOSED_OPTION);
            txthoten.requestFocus();
            txthoten.setBackground(Color.red);
            return false;
        }
        if (email.length() == 0) {
            JOptionPane.showConfirmDialog(this, "Bạn chưa nhập địa chỉ email !", "TB", JOptionPane.CLOSED_OPTION);
            txtemail.requestFocus();
            txtemail.setBackground(Color.red);
            return false;
        }
        if (sdt.length() == 0) {
            JOptionPane.showConfirmDialog(this, "Bạn chưa nhập số điện thoại !", "TB", JOptionPane.CLOSED_OPTION);
            txtsdt.requestFocus();
            txtsdt.setBackground(Color.red);
            return false;
        }
        if (dc.length() == 0) {
            JOptionPane.showConfirmDialog(this, "Bạn chưa nhập địa chỉ !", "TB", JOptionPane.CLOSED_OPTION);
            txtdiachi.requestFocus();
            txtdiachi.setBackground(Color.red);
            return false;
        }
        if (!rdnam.isSelected() && !rdnu.isSelected()) {
            JOptionPane.showConfirmDialog(this, "Bạn chưa nhập Giới Tính !", "TB", JOptionPane.CLOSED_OPTION);
            rdnam.setBackground(Color.red);
            rdnu.setBackground(Color.red);
            return false;
        }

        //kiem tra mail
        // String rex = "^\\w+[a-z0-9]*@{1}\\w+mail.com$";
        String rex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        if (!email.matches(rex)) {
            txtemail.requestFocus();
            txtemail.setBackground(Color.red);
            tbemail.setText("email phải có dạng ...@...mail.com");
            return false;
        }

        //kiem tra sdt
        String Rexsdt = "^0+\\d{9}";
        if (!sdt.matches(Rexsdt)) {
            JOptionPane.showConfirmDialog(this, "SĐT Bạn nhập không hợp lệ !", "TB", JOptionPane.CLOSED_OPTION);
            txtsdt.requestFocus();
            txtsdt.setBackground(Color.red);
            tbsđt.setText("bắt đầu từ số 0, đủ 10 số");
            return false;
        }
        String Rexmssv = "\\d{8}";
        if (!id.matches(Rexmssv)) {
            JOptionPane.showConfirmDialog(this, "Mssv Bạn nhập không hợp lệ !", "TB", JOptionPane.CLOSED_OPTION);
            txtmasv.requestFocus();
            txtmasv.setBackground(Color.red);
            tbmssv.setText("mssv phải đủ 8 số");
            return false;
        }
        return true;

    }
    public SinhVien getModel() {
        SinhVien sv = new SinhVien();
        String d = (String) cbblop.getSelectedItem();
        lop g = new lop();
        g.setMalop(d);
        sv.setLop(g);
        sv.setMasv(txtmasv.getText());
        sv.setTensv(txthoten.getText());
        boolean gt = false;
        if (rdnam.isSelected()) {
            gt = true;
        }
        sv.setGioitinh(gt);
        sv.setSdt(txtsdt.getText());
        sv.setEmail(txtemail.getText());
        sv.setDiachi(txtdiachi.getText());
        return sv;
    }
    private void btnluuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluuActionPerformed
        // TODO add your handling code here:
        if (check()) {
            SinhVien sv = getModel();
            if (dao.laysvtheomasv(sv.getMasv()) != null) {
                JOptionPane.showMessageDialog(this, "MSSV đã có. Hãy nhập mssv khác");
            } else{
                if (dao.themsv(sv) > 0) {
                JOptionPane.showMessageDialog(this, "Thêm mới thành công");
                txtmasv.setText("");
                txthoten.setText("");
                txtemail.setText("");
                txtdiachi.setText("");
                txtsdt.setText("");
                txtmasv.setBackground(Color.white);
                txthoten.setBackground(Color.white);
                txtdiachi.setBackground(Color.white);
                txtsdt.setBackground(Color.white);
                txtemail.setBackground(Color.white);
                tbmssv.setText("");
                tbemail.setText("");
                tbsđt.setText("");
            }
            }
        }
    }//GEN-LAST:event_btnluuActionPerformed

    private void rdnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdnuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdnuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbblopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbblopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbblopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Themsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Themsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Themsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Themsv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Themsv dialog = new Themsv();

                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnluu;
    private javax.swing.JComboBox<String> cbblop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdnam;
    private javax.swing.JRadioButton rdnu;
    private javax.swing.JLabel tbemail;
    private javax.swing.JLabel tbmssv;
    private javax.swing.JLabel tbsđt;
    private javax.swing.JTextArea txtdiachi;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txtmasv;
    private javax.swing.JTextField txtsdt;
    // End of variables declaration//GEN-END:variables
}
